// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/11/2024, 3:02:39 PM
const configMerger = require("/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/plugins/**/*.{js,ts,mjs}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/composables/**/*.{js,ts,mjs}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/utils/**/*.{js,ts,mjs}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "/Users/judith.b/Desktop/24-25/LUCA/WEB-DESIGN/portfolioWeb/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})()
